services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - data-stream-net

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - data-stream-net

  airflow:
    image: puckel/docker-airflow:1.10.9
    restart: always
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      - LOAD_EX=y
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./app:/usr/local/airflow/app
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - data-stream-net

  scheduler:
    image: puckel/docker-airflow:1.10.9
    restart: always
    depends_on:
      - kafka
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./app:/usr/local/airflow/app
    command: scheduler
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - data-stream-net

networks:
  data-stream-net:
    driver: bridge
